server:
  port: 8080
  servlet:
    context-path: /api # 所有的接口统一加/api前缀，方便前端代理

spring:
  application:
    name: shop-vault

  # 1.数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/shop-vault # 数据库名: shop-vault
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # 数据库账号
    password: root # 数据库密码

  # 2.Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: foobared #Redis密码

  # 3.文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# 4.MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # MapperXML扫描路径
  type-aliases-package: com.TsukasaChan.ShopVault.entity # 实体类包别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL打印，方便调试
    map-underscore-to-camel-case: true # 开启下划线转驼峰

# 5.自定义配置(供代码读取)
shop-vault:
  jwt:
    secret: shopvault_secret_key_2026_grad_project_secret # JWT密钥
    expiration: 3600000 # 3600000毫秒(1小时)
    token-header: Authorization
  YOLO:
    url: http://localhost:5000/predict # Python YOLO服务的地址
  upload:
    path: D:/shop-vault/uploads/ # 本地文件存储路径

# 6. 日志级别
logging:
  level:
    com.shopvault: debug
    org.springframework: info
